### ISSUE TITLE
Community Section Broken

### ISSUE THREAD

**Issue by amanharwara** [jgchk/RateYourMusic-Dark#1]
Nice theme.
The "New Post" page and the right side column on the community pages are broken.

![2020-02-20 22_17_24-Window](https://user-images.githubusercontent.com/8348101/74958379-d9f28580-542e-11ea-8472-fc1af9eb417e.png)
![2020-02-20 22_17_44-Window](https://user-images.githubusercontent.com/8348101/74958382-db23b280-542e-11ea-8479-cea77bd93dea.png)

I'll try and see if I can fix them and I'll create a PR if possible.

**Comment by jgchk** [comment]
thank you for the report and fix!
I've merged the changes :)
